#pragma once

//Colors and shades (32x: 27x colors + 5x others).
#define c_dkgray 0x404040
#define c_ltgray 0xC0C0C0
#define c_brown 0x004080
//#define c_ 0x
//#define c_ 0x
#define c_black      0x000000
#define c_maroon     0x000080
#define c_red        0x0000FF
#define c_green      0x008000
#define c_olive      0x008080
#define c_orange     0x0080FF
#define c_lime       0x00FF00
#define c_chartreuse 0x00FF80
#define c_yellow     0x00FFFF
#define c_navy       0x800000
#define c_purple     0x800080
#define c_rose       0x8000FF
#define c_teal       0x808000
#define c_gray       0x808080
#define c_salmon     0x8080FF
#define c_seagreen   0x80FF00
#define c_mint       0x80FF80
#define c_golden     0x80FFFF
#define c_blue       0xFF0000
#define c_violet     0xFF0080
#define c_fuchsia    0xFF00FF
#define c_sky        0xFF8000
#define c_istante    0xFF8080
#define c_pink       0xFF80FF
#define c_aqua       0xFFFF00
#define c_ice        0xFFFF80
#define c_white      0xFFFFFF

//I/O
//Keyboard symbols
#define vk_a SDL_SCANCODE_A
#define vk_b SDL_SCANCODE_B
#define vk_c SDL_SCANCODE_C
#define vk_d SDL_SCANCODE_D
#define vk_e SDL_SCANCODE_E
#define vk_f SDL_SCANCODE_F
#define vk_g SDL_SCANCODE_G
#define vk_h SDL_SCANCODE_H
#define vk_i SDL_SCANCODE_I
#define vk_j SDL_SCANCODE_J
#define vk_k SDL_SCANCODE_K
#define vk_l SDL_SCANCODE_L
#define vk_m SDL_SCANCODE_M
#define vk_n SDL_SCANCODE_N
#define vk_o SDL_SCANCODE_O
#define vk_p SDL_SCANCODE_P
#define vk_q SDL_SCANCODE_Q
#define vk_r SDL_SCANCODE_R
#define vk_s SDL_SCANCODE_S
#define vk_t SDL_SCANCODE_T
#define vk_u SDL_SCANCODE_U
#define vk_v SDL_SCANCODE_V
#define vk_w SDL_SCANCODE_W
#define vk_x SDL_SCANCODE_X
#define vk_y SDL_SCANCODE_Y
#define vk_z SDL_SCANCODE_Z
#define vk_0 SDL_SCANCODE_0
#define vk_1 SDL_SCANCODE_1
#define vk_2 SDL_SCANCODE_2
#define vk_3 SDL_SCANCODE_3
#define vk_4 SDL_SCANCODE_4
#define vk_5 SDL_SCANCODE_5
#define vk_6 SDL_SCANCODE_6
#define vk_7 SDL_SCANCODE_7
#define vk_8 SDL_SCANCODE_8
#define vk_9 SDL_SCANCODE_9
//Keyboard keys
#define vk_escape SDL_SCANCODE_ESCAPE
#define vk_space SDL_SCANCODE_SPACE
#define vk_enter SDL_SCANCODE_RETURN
#define vk_backspace SDL_SCANCODE_BACKSPACE
#define vk_tab SDL_SCANCODE_TAB
#define vk_insert SDL_SCANCODE_INSERT
#define vk_delete SDL_SCANCODE_DELETE
#define vk_home SDL_SCANCODE_HOME
#define vk_end SDL_SCANCODE_END
#define vk_pageup SDL_SCANCODE_PAGEUP
#define vk_pagedown SDL_SCANCODE_PAGEDOWN
#define vk_left SDL_SCANCODE_LEFT
#define vk_right SDL_SCANCODE_RIGHT
#define vk_up SDL_SCANCODE_UP
#define vk_down SDL_SCANCODE_DOWN
//#define vk_ SDL_SCANCODE_
//#define vk_ SDL_SCANCODE_
//#define vk_ SDL_SCANCODE_

//#define vk_ SDL_SCANCODE_
#define vk_f1 SDL_SCANCODE_F1
#define vk_f2 SDL_SCANCODE_F2
#define vk_f3 SDL_SCANCODE_F3
#define vk_f4 SDL_SCANCODE_F4
#define vk_f5 SDL_SCANCODE_F5
#define vk_f6 SDL_SCANCODE_F6
#define vk_f7 SDL_SCANCODE_F7
#define vk_f8 SDL_SCANCODE_F8
#define vk_f9 SDL_SCANCODE_F9
#define vk_f10 SDL_SCANCODE_F10
#define vk_f11 SDL_SCANCODE_F11
#define vk_f12 SDL_SCANCODE_F12
#define vk_f13 SDL_SCANCODE_F13
#define vk_f14 SDL_SCANCODE_F14
#define vk_f15 SDL_SCANCODE_F15
#define vk_f16 SDL_SCANCODE_F16
#define vk_f17 SDL_SCANCODE_F17
#define vk_f18 SDL_SCANCODE_F18
#define vk_f19 SDL_SCANCODE_F19
#define vk_f20 SDL_SCANCODE_F20
#define vk_f21 SDL_SCANCODE_F21
#define vk_f22 SDL_SCANCODE_F22
#define vk_f23 SDL_SCANCODE_F23
#define vk_f24 SDL_SCANCODE_F24

//Keyboard modifiers.
#define vk_ctrl KMOD_CTRL
#define vk_shift KMOD_SHIFT
#define vk_alt KMOD_ALT
